# Generated by Django 4.2.4 on 2024-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.CharField(default='', max_length=15),
        ),
    ]
